[supervisord]
nodaemon=true

[program:api]
command=/usr/local/bin/uvicorn app.main:app --host 127.0.0.1 --port 8000
directory=/app
user=root
autorestart=true
priority=10

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=20
